[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^6.21.3

[env:native]
platform = native
build_flags =
	-D SIMULATION_MODE=1